steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - fetch-btc-price  # <-- your function name
      - --runtime=python310
      - --trigger-http
      - --entry-point=main
      - --source=cloud_function/
      - --region=asia-southeast1
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
