# Cloud Function: fetch_btc_price
# Runtime: Python 3.11 (Gen 2)
# Purpose: Fetch BTC price data, simulate 10k records, store as parquet in GCS

name: fetch_btc_price
description: |
  Ingests Bitcoin price, simulates 10,000 records, converts to Parquet, and uploads to GCS.

deployment:
  region: asia-southeast1
  project: crypto-etl-project-465203
  runtime: python311
  entry_point: fetch_btc_price
  source: .
  trigger: http
  allow_unauthenticated: true
  environment: gen2
  memory: 256MiB
  timeout: 60s
