steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy fetch_btc_price \
          --region=asia-southeast1 \
          --runtime=python311 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=fetch_btc_price \
          --source=. \
          --timeout=60s \
          --memory=256MB \
          --project=crypto-etl-project-465203

timeout: 300s